#ifndef CONFIG_H
#define CONFIG_H

#define BUS_STATION_NAME "Bến Bạch Đằng"
#define BUS_STATION_ADDRESS "21, Đường Tôn Đức Thắng, Quận 1"
#define BUS_STATION_LONGITUDE 106.801802
#define BUS_STATION_LATITUDE 10.880422

#define DURATION_CHECK_BUS_STATUS 2000
#define DURATION_TO_REMOVE_BUS_FROM_LIST 4000

#define DURATION_RESEND_LORA_DATA 2000
#define TIMES_RESEND_LORA_DATA 10

#define STATION_ID 59001

#endif // CONFIG_H
