#ifndef __COMMON__H__
#define __COMMON__H__

#define BUS_ID 1
#define ROUTE_ID 53

#define DURATION_READ_DHT11 2000
#define DURATION_READ_GPS 100
#define DURATION_SEND_LORA 4000
#define DURATION_RECEIVE_LORA 10

#define START_BYTE '*'
#define END_BYTE '#'
#define MAX_RCV_BUFFER 100

#define DISTANCE_THRESHOLD 30
#define NO_OF_DISTANCE_DEBOUNCING 3
#define NO_TIMES_GET_DEFAULT_DISTANCE 10
#define DISTANCE_THRESHOLD_RATE 0.8
#define THRESHOLD_DETERMINE_PEOPLE_MS 2000

#define MAX_PEOPLES_IN_BUS 10

#define NO_OF_BUTTON_DEBOUNCING 3

#define STOP_MSG_NUMBER 2024

#endif
